# Generated by Django 5.2.3 on 2025-08-12 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackform',
            name='form_type',
            field=models.CharField(choices=[('empty', 'Empty Form'), ('customer_satisfaction', 'Customer Satisfaction'), ('employee_feedback', 'Employee Feedback'), ('product_feedback', 'Product Feedback'), ('service_feedback', 'Service Feedback'), ('general', 'General Feedback')], default='general', max_length=50),
        ),
    ]
